services:
  - type: web
    name: job-posting-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_USER
        value: your-db-user
      - key: DB_PASS
        value: your-db-password
      - key: DB_NAME
        value: your-db-name
